export const FETCH_POST_BEGIN = "FETCH_POST_BEGIN";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const FETCH_SINGLE_POST_BEGIN = "FETCH_SINGLE_POST_BEGIN";
export const FETCH_SINGLE_POST_SUCCESS = "FETCH_SINGLE_POST_SUCCESS";
export const FETCH_SINGLE_POST_FAILURE = "FETCH_SINGLE_POST_FAILURE";

export const POST_VOTE_SUCCESS = "POST_LIKE_SUCCESS";

export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";

export const ADD_POST_BEGIN = "ADD_POST_BEGIN";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";
